---
name: Expo Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v4
        with:
          expo-version: 3.x
          expo-username: bycedric
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-packager: yarn
      - run: expo --help
      - run: expo whoami
      - run: npm ci
      - run: expo publish
