---
name: Expo Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: mkdir -p /opt/hostedtoolcache/expo-cli/3.4.1/x64
      - uses: actions/cache@preview
        with:
          path: /opt/hostedtoolcache/expo-cli/3.4.1/x64
          key: ${{ runner.os }}-expo-cli-attempt-2-3.4.1
          restore-keys: |
            ${{ runner.os }}-expo-cli-attempt-2-
      - uses: expo/expo-github-action@v4
        with:
          expo-version: 3.4.1
          expo-username: bycedric
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: expo --help
      - run: expo whoami
